### ISSUE TITLE
H matrix dimension

### ISSUE THREAD

**Issue by wang701** [auralius/kalman-cpp#6]
Hi @auralius,

Thanks for this library. Trying to some prototyping work with this. I am new to both Armadillo and C++ so I have a question.

For [this line](https://github.com/auralius/kalman-cpp/blob/master/samples/main3.cpp#L35), why is H a 4x2 matrix? Shouldn't it be 2x4 given that your X is 4x1?

Let me know if I missed anything obvious.

**Comment by auralius** [comment]
Hi @wang701 
Thanks for spotting the mistake, You are right. However, in [line 44](https://github.com/auralius/kalman-cpp/blob/521b3cef13728b87195f730013fe3d0ffdad233e/samples/main3.cpp#L44), it gets overwritten by a 2x4 matrix.

Nevertheless, it has to be fixed.
